### ISSUE TITLE
Reasons for the secondary combination of regional features and attention weights

### ISSUE THREAD

**Issue by hongyan-an** [Artanic30/MacCap#1]
Great work！I have the following questions, in the last operation to obtain the region feature,  the attention weight is  the attention weight of the previous layer ? if so, the patch token already obtained by interacting with the attention weight A, is it just to obtain the mutual information between valid patch tokens here?

**Comment by Artanic30** [comment]
Hi, thanks for your interest in our work. Regarding your first question, the attention weight used in the last operation to obtain the region feature is indeed from the last layer of the CLIP ViT visual patch feature. For the second question, your understanding is correct. Please let me know if you have further questions.

**Comment by hongyan-an** [comment]
> Hi, thanks for your interest in our work. Regarding your first question, the attention weight used in the last operation to obtain the region feature is indeed from the last layer of the CLIP ViT visual patch feature. For the second question, your understanding is correct. Please let me know if you have further questions.

Thanks for your answer!
